[project]
name = "dl-practitioner"
version = "0.1.0"
description = "Deep Learning Practitioner Course"
requires-python = ">=3.11"
dependencies = [
    "ai-edge-litert>=2.2.0",
    "directory-tree>=1.0.0",
    "fastbook>=0.0.29",
    "ipywidgets>=7.8.5",
    "jupyter>=1.1.1",
    "lightning>=2.6.5",
    "matplotlib==3.9.0",
    "mlflow>=3.15.1",
    "numpy==2.3.2",
    "onnx>=1.22.0",
    "onnx-graphsurgeon>=0.6.1",
    "onnx2tf>=1.28.8",
    "onnxruntime>=1.28.0",
    "optuna>=4.9.0",
    "pillow==11.3.0",
    "scikit-learn>=1.7.2",
    "sng4onnx>=2.0.1",
    "tensorflow>=2.21.0",
    "tf-keras>=2.21.0",
    "torch==2.6.0",
    "torchmetrics>=1.9.0",
    "torchvision==0.21.0",
    "tqdm>=4.67.1",
    "transformers>=4.57.1",
]
